export const SEND_MESSAGE_REQUESTED = "weather.SEND_MESSAGE_REQUESTED";
export const SEND_MESSAGE_SUCCEEDED = "weather.SEND_MESSAGE_SUCCEEDED";
export const SEND_MESSAGE_FAILED = "weather.SEND_MESSAGE_FAILED";
