export const DAILY_OBSERVATIONS_REQESTED = "weather.DAILY_OBSERVATIONS_REQESTED";
export const DAILY_OBSERVATIONS_SUCCEEDED = "weather.DAILY_OBSERVATIONS_SUCCEEDED";
export const DAILY_OBSERVATIONS_FAILED = "weather.DAILY_OBSERVATIONS_FAILED";


export const FETCH_FIELD_REQESTED = "weather.FETCH_FIELD_REQESTED";
export const FETCH_FIELD_SUCCEEDED = "weather.FETCH_FIELD_SUCCEEDED";
export const FETCH_FIELD_FAILED = "weather.FETCH_FIELD_FAILED";