export const DAILY_OBSERVATIONS_REQUESTED = "weather.DAILY_OBSERVATIONS_REQUESTED";
export const DAILY_OBSERVATIONS_SUCCEEDED = "weather.DAILY_OBSERVATIONS_SUCCEEDED";
export const DAILY_OBSERVATIONS_FAILED = "weather.DAILY_OBSERVATIONS_FAILED";

export const FETCH_FIELD_REQUESTED = "weather.FETCH_FIELD_REQUESTED";
export const FETCH_FIELD_SUCCEEDED = "weather.FETCH_FIELD_SUCCEEDED";
export const FETCH_FIELD_FAILED = "weather.FETCH_FIELD_FAILED";

export const FETCH_COUNTY_WARDS_REQUESTED = "weather.FETCH_COUNTY_WARDS_REQUESTED";
export const FETCH_COUNTY_WARDS_SUCCEEDED = "weather.FETCH_COUNTY_WARDS_SUCCEEDED";
export const FETCH_COUNTY_WARDS_FAILED = "weather.FETCH_COUNTY_WARDS_FAILED";

export const ADD_WARD_WIDGET_REQUESTED = "weather.ADD_WARD_WIDGET_REQUESTED";
export const ADD_WARD_WIDGET_SUCCEEDED = "weather.ADD_WARD_WIDGET_SUCCEEDED";
export const ADD_WARD_WIDGET_FAILED = "weather.ADD_WARD_WIDGET_FAILED";

